language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  # Tagging
  - docker tag udagram-reverseproxy tandev2k/reverseproxy:v1
  - docker tag udagram-api-feed tandev2k/udagram-api-feed:v1
  - docker tag udagram-api-user tandev2k/udagram-api-user:v1
  - docker tag udagram-frontend tandev2k/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tandev2k/udagram-reverseproxy:v1
  - docker push tandev2k/udagram-api-feed:v1
  - docker push tandev2k/udagram-api-user:v1
  - docker push tandev2k/udagram-frontend:v1
